### ISSUE TITLE
:erlang.now() is deprecated in Erlang 18

### ISSUE THREAD

**Issue by mitchellhenke** [grempe/ex_rated#1]
http://www.erlang.org/doc/apps/erts/time_correction.html#Dos_and_Donts_Retrieve_Erlang_System_Time

Timex does this:
https://github.com/bitwalker/timex/blob/master/lib/utils/utils.ex#L8
https://github.com/bitwalker/timex/blob/141fff64f0c806f523ef0b8b0d66b5d14c002ab1/lib/time/time.ex#L237

if something like that sounds good to you, I can give it a shot :)

**Comment by grempe** [comment]
Sure Mitchell, give it a go!

Cheers

Glenn

**Comment by mitchellhenke** [comment]
cool, I'll hopefully be able to start on this soon

**Comment by grempe** [comment]
New version 0.0.6 pushed to hex.pm.  Thanks for the enhancement.

https://hex.pm/packages/ex_rated/0.0.6

**Comment by mitchellhenke** [comment]
you bet!
