### ISSUE TITLE
ExRated.check_rate should return the time until the bucket is reset

### ISSUE THREAD

**Issue by ShaneWilton** [grempe/ex_rated#12]
Right now, if `ExRated.check_rate` returns an error, it returns `{:error, limit}`. This makes it difficult to efficiently handle actions that get rejected due to rate limits. If we instead return a tuple like `{:error, limit, time_until_next_bucket_reset}`, then it would be possible for the caller to schedule the action for the earliest possible point that it may next succeed at.

I'm happy to take a stab at this if you let me know what specific interface you'd like to support, or if you have any other ideas on handling this use-case.

Thanks! I love the hex :)

**Comment by grempe** [comment]
I think maybe you are looking for inspect_bucket/3 which was implemented in a pull request a few months back.  Does this cover your use case?

https://github.com/grempe/ex_rated/pull/7

Glad you are enjoying this.  I am not actively using Elixir now (wish I was sometimes) so glad its holding up for you.

Glenn

**Comment by ShaneWilton** [comment]
I saw inspect, but it isn't atomic, as far as I can tell. I can't see if
tokens are available, and increment the counter in one operation.

**Comment by grempe** [comment]
Yes, that is the way it is now.  The reason for not changing the return result of check_rate before was to avoid a breaking API change, and the thought was that if your check rate request is rejected you could follow up to the inspect_bucket to get the info you need to schedule something, or do whatever you needed.

Is your use case so granular that the additional call would give you a different result that if you got the info in a single call?  i am curious.

If you want to propose the specifics and are willing to do a pull request with tests and docs I'd be open to something that improves real world use.

Thanks for your interest.

**Comment by ShaneWilton** [comment]
Yeah, you're totally right. Thinking further about the issue, the worst case scenario is just an individual action waiting slightly longer than it otherwise might have, which isn't really something to worry about.

Thanks for your input, I'll close this ticket now :)

**Comment by grempe** [comment]
Yeah the second call will probably only take about 5 microseconds (not milliseconds) according to quick perf testing so they won't be waiting too long 😀

I do agree though that when the API was originally created it would have been nice to include this info in the result.
