### ISSUE TITLE
Memory leak problem

### ISSUE THREAD

**Issue by dsnipe** [grempe/ex_rated#19]
Hey!  
Thanks for a great library.  
We use it in production under high load, but after one month or so we experienced out of memory on the server. We found that the reason is this library.
Our usage example (it's a plug):
```
# SKIP
  defp check_rate(conn, options) do
    interval_milliseconds = options[:interval_seconds] * 1000
    max_requests = options[:max_requests]
    ExRated.check_rate(bucket_name(conn), interval_milliseconds, max_requests)
  end

  # Bucket name should be a combination of ip address and request path, like so:
  #
  # "127.0.0.1:/api/v1/authorizations"
  defp bucket_name(conn) do
    path = Enum.join(conn.path_info, "/")
    ip   = conn.remote_ip |> Tuple.to_list |> Enum.join(".")
    "#{ip}:#{path}"
  end
# SKIP
```
And configurations: `config :ex_rated, :timeout, 600_000`
In my controller: `plug MyApp.Plug.RateLimit, max_requests: 5, interval_seconds: 60`

Maybe you have any ideas what might be a problem? Of course I'll try to investigate it and if I find a solution, will create a PR.

**Comment by grempe** [comment]
Interesting. No I don't have any idea why, and I have not been actively using or maintaining this lib to be honest so if you do find a reason a pull request would be greatly appreciated!

**Comment by sergiotapia** [comment]
@dsnipe This uses ETS for saving bucket information - could it be you're never purging stale bucket data?

**Comment by ryanwinchester** [comment]
@dsnipe did you ever solve this. I wanted to use this in a production application as well, but now I'm scared to.

**Comment by grempe** [comment]
I'll mark this as `help wanted` as I don't currently have the time to investigate. I suspect there is an edge case at play here though as this lib has been used by others in production for a couple of years now with no similar reports.

@dsnipe Can you provide more information as to how you determined that it was this lib that was seemingly at fault for your server memory issue?

There is an automatic pruning process for old ETS records which should limit the growth of the ETS tables with old buckets.

**Comment by sergiotapia** [comment]
@grempe There's also the issue where adding ex_rated to a Phoenix project essentially turns the application single-threaded since every request goes through the exrated genserver. It becomes a bottleneck.

**Comment by jaimeiniesta** [comment]
@sergiotapia can you please elaborate further in a separate issue? If if makes *every* request pass through the exrated bottleneck, then that's serious.

**Comment by ryanwinchester** [comment]
https://dockyard.com/blog/2017/05/19/optimizing-elixir-and-phoenix-with-ets

**Comment by sergiotapia** [comment]
@jaimeiniesta It makes every single request go through the single genserver process. It is really bad. I didn't notice this issue but Chris McCord mentioned it to me and said it was a major problem; turning Phoenix apps into a single-threaded app.

**Comment by dsnipe** [comment]
It turned out that ex_rated wasn't a problem. I can close the issue.

**Comment by dsnipe** [comment]
Thank you everyone and sorry for a false alarm.

**Comment by sergiotapia** [comment]
@jaimeiniesta Yes, every single request that uses exrated.
