### ISSUE TITLE
Both a daily and requests per second (throttle) scale and limit?

### ISSUE THREAD

**Issue by ryanwinchester** [grempe/ex_rated#21]
If I wanted to do _both_ a **daily** and a **per-second** `limit`, do I need two separate buckets?

**Comment by grempe** [comment]
Yes. Something like:

```
ExRated.check_rate("my-five-per-second-bucket", 1000, 5)
```

and

```
ExRated.check_rate("my-1000-per-day-bucket", 86400000, 1000)
```

Then check both every time you check the thing you want to limit.
