### ISSUE TITLE
Genserver name is hardcoded to :ex_rated

### ISSUE THREAD

**Issue by jonzlin95** [grempe/ex_rated#22]
Firstly thanks for your great work on this library. Been using it to lots of success in production thus far. I'm currently trying to get multiple nodes to work, but I noticed in the code that the Genserver calls are hardcoded to use the tuple :ex_rated, regardless of the configuration passed into the Genserver start.

https://github.com/grempe/ex_rated/blob/master/lib/ex_rated.ex

Thanks

**Comment by grempe** [comment]
Thanks, glad you are using it productively. As to your suggestion, I am not currently active in maintaining this library. I will look at merging in pull requests that are comprehensive (docs, tests, etc). So if this change is valuable to you that would be the suggested path.

**Comment by grempe** [comment]
Closing stale feature request
