### ISSUE TITLE
performance improvement

### ISSUE THREAD

**Issue by ruslandoga** [grempe/ex_rated#88]
👋 @grempe 

I wonder if you'd be open to accepting a PR improving performance ~5x by using the approach similar to https://github.com/ExHammer/hammer/pull/72?

https://github.com/ruslandoga/rate_limit contains some benchmarks, the "new" approach is `counters` which is based on `plug_attack`

**Comment by ruslandoga** [comment]
I skimmed the current source code and it doesn't seem like there are any changes to the public API required.

**Comment by grempe** [comment]
Hi @ruslandoga 

Thanks for the interest but at this moment I'd rather not replace the core of ex_rated with code that I am not familiar with. I no longer use Elixer actively and I'd want to fully understand and use any new code to be a responsible steward.

You are free of course to fork the existing code under its license and publish a new version.

Cheers
